spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:produtos
    username: patrick
    password: senha
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console