spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:produtos # Banco em memória (padrão)
    username: patrick
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect #Cria/atualiza tabelas automaticamente
  h2:
    console:
      enabled: true # Ativa o console web do H2
      path: /h2-console # URL do console